<?php
require __DIR__.'/app/bootstrap.php'; require __DIR__.'/app/layout.php';
$user=require_permission('manage_roles'); $pdo=db();
if($_SERVER['REQUEST_METHOD']==='POST'){
    verify_csrf(); $action=$_POST['action']??'';
    if($action==='permission'){$pdo->prepare('INSERT INTO role_permissions(role_id,permission_id,granted) VALUES(?,?,?) ON DUPLICATE KEY UPDATE granted=VALUES(granted)')->execute([(int)$_POST['role_id'],(int)$_POST['permission_id'],isset($_POST['granted'])?1:0]);}
    if($action==='user'&&user_can('manage_users')){$pdo->prepare('UPDATE users SET role_id=?,is_active=? WHERE id=?')->execute([(int)$_POST['role_id'],isset($_POST['is_active'])?1:0,(int)$_POST['user_id']]);}
    redirect('admin.php');
}
$roles=$pdo->query('SELECT * FROM roles ORDER BY id')->fetchAll(); $permissions=$pdo->query('SELECT * FROM permissions ORDER BY id')->fetchAll(); $grants=[];
foreach($pdo->query('SELECT * FROM role_permissions') as $grant)$grants[$grant['role_id']][$grant['permission_id']]=$grant['granted'];
$users=$pdo->query('SELECT u.*,r.name role_name FROM users u JOIN roles r ON r.id=u.role_id ORDER BY u.full_name')->fetchAll(); page_start('Roles & Access',$user); ?>
<div class="page-head"><div><p class="eyebrow">Super Admin</p><h1>Roles &amp; Access Management</h1><p class="page-subtitle">Changes apply immediately to new requests.</p></div></div>
<section><h2>Role permissions</h2><div class="table-wrap"><table class="ticket-table"><thead><tr><th>Permission</th><?php foreach($roles as $role):?><th><?=e($role['name'])?></th><?php endforeach;?></tr></thead><tbody><?php foreach($permissions as $permission):?><tr><td><strong><?=e($permission['label'])?></strong><br><span class="muted"><?=e($permission['description'])?></span></td><?php foreach($roles as $role):?><td><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="permission"><input type="hidden" name="role_id" value="<?=$role['id']?>"><input type="hidden" name="permission_id" value="<?=$permission['id']?>"><input type="checkbox" name="granted" onchange="this.form.submit()" <?=$grants[$role['id']][$permission['id']]??false?'checked':''?> aria-label="<?=e($role['name'].' '.$permission['label'])?>"></form></td><?php endforeach;?></tr><?php endforeach;?></tbody></table></div></section>
<section><h2>Users</h2><div class="table-wrap"><table class="ticket-table"><thead><tr><th>Name</th><th>Username</th><th>Role</th><th>Active</th><th>Save</th><th>Reset password</th></tr></thead><tbody><?php foreach($users as $member):?><tr><td><?=e($member['full_name'])?></td><td><?=e($member['username'])?></td><td><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="user"><input type="hidden" name="user_id" value="<?=$member['id']?>"><select name="role_id"><?php foreach($roles as $role):?><option value="<?=$role['id']?>" <?=$member['role_id']==$role['id']?'selected':''?>><?=e($role['name'])?></option><?php endforeach;?></select></td><td><input type="checkbox" name="is_active" <?=$member['is_active']?'checked':''?>></td><td><button class="button">Save</button></form></td><td><a href="reset-user-password.php?id=<?=$member['id']?>">Reset</a></td></tr><?php endforeach;?></tbody></table></div></section><?php page_end();
