<?php
require __DIR__ . '/app/bootstrap.php'; require __DIR__ . '/app/layout.php';
$admin = require_login();
if (($admin['role_slug'] ?? '') !== 'super-admin') { http_response_code(403); exit('Super Admin access required.'); }
$pdo = db(); $error = ''; $notice = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    verify_csrf(); $action = (string) ($_POST['action'] ?? ''); $type = (string) ($_POST['type'] ?? ''); $id = (int) ($_POST['id'] ?? 0);
    try {
        if ($action === 'delete' && $type === 'event') { $pdo->prepare('DELETE FROM calendar_events WHERE id=?')->execute([$id]); audit_admin_action((int)$admin['id'],'calendar_event_deleted','calendar_event',$id); $notice='Event deleted.'; }
        elseif ($action === 'delete' && $type === 'holiday') { $pdo->prepare('DELETE FROM company_holidays WHERE id=?')->execute([$id]); audit_admin_action((int)$admin['id'],'company_holiday_deleted','company_holiday',$id); $notice='Holiday deleted.'; }
        elseif ($action === 'edit' && $type === 'event') { $title=trim((string)($_POST['title']??''));$date=(string)($_POST['event_date']??'');$end=trim((string)($_POST['end_date']??''));$eventType=(string)($_POST['event_type']??'');if($title===''||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date)||($end!==''&&$end<$date)||!in_array($eventType,['team_event','coverage','reminder','other'],true))throw new InvalidArgumentException('Enter valid event details.');$pdo->prepare('UPDATE calendar_events SET title=?,event_date=?,end_date=?,event_type=? WHERE id=?')->execute([$title,$date,$end?:null,$eventType,$id]);audit_admin_action((int)$admin['id'],'calendar_event_updated','calendar_event',$id,['title'=>$title,'event_date'=>$date]);$notice='Event updated.'; }
        elseif ($action === 'edit' && $type === 'holiday') { $label=trim((string)($_POST['label']??''));$date=(string)($_POST['date']??'');$country=(string)($_POST['country_code']??'');if($label===''||!preg_match('/^\d{4}-\d{2}-\d{2}$/',$date)||!in_array($country,['COMPANY','PH','AU','CA'],true))throw new InvalidArgumentException('Enter valid holiday details.');$pdo->prepare('UPDATE company_holidays SET `date`=?,label=?,country_code=?,holiday_type=? WHERE id=?')->execute([$date,$label,$country,$country==='COMPANY'?'company':'public',$id]);audit_admin_action((int)$admin['id'],'company_holiday_updated','company_holiday',$id,['date'=>$date,'label'=>$label,'country_code'=>$country]);$notice='Holiday updated.'; }
    } catch (Throwable $exception) { $error=$exception instanceof InvalidArgumentException?$exception->getMessage():'Calendar change could not be saved.'; }
}
$events=$pdo->query('SELECT * FROM calendar_events ORDER BY event_date DESC, id DESC')->fetchAll();$holidays=$pdo->query('SELECT * FROM company_holidays ORDER BY `date` DESC, id DESC')->fetchAll();
page_start('Calendar administration',$admin); ?><div class="page-head"><div><p class="eyebrow">Super Admin</p><h1>Calendar administration</h1><p class="page-subtitle">Edit or delete calendar events and company/public holidays.</p></div></div><?php if($error):?><p class="auth-error"><?=e($error)?></p><?php endif;?><?php if($notice):?><p class="action-notice"><?=e($notice)?></p><?php endif;?><section><h2>Events</h2><?php foreach($events as $event):?><form method="post" class="compact-form"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="edit"><input type="hidden" name="type" value="event"><input type="hidden" name="id" value="<?=$event['id']?>"><label>Title<input name="title" value="<?=e($event['title'])?>" required></label><label>Type<select name="event_type"><?php foreach(['team_event'=>'Team event','coverage'=>'Coverage','reminder'=>'Reminder','other'=>'Other'] as $key=>$label):?><option value="<?=$key?>" <?=$event['event_type']===$key?'selected':''?>><?=e($label)?></option><?php endforeach;?></select></label><label>Start<input type="date" name="event_date" value="<?=e($event['event_date'])?>" required></label><label>End<input type="date" name="end_date" value="<?=e($event['end_date']??'')?>"></label><button class="button">Save</button><button class="button button-danger" name="action" value="delete" formnovalidate data-confirm="Delete this event?">Delete</button></form><?php endforeach;?><?php if(!$events):?><p class="muted">No events.</p><?php endif;?></section><section><h2>Holidays</h2><?php foreach($holidays as $holiday):?><form method="post" class="compact-form"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="type" value="holiday"><input type="hidden" name="id" value="<?=$holiday['id']?>"><label>Label<input name="label" value="<?=e($holiday['label'])?>" required></label><label>Country<select name="country_code"><?php foreach(['COMPANY'=>'Company','PH'=>'Philippines','AU'=>'Australia','CA'=>'Canada'] as $key=>$label):?><option value="<?=$key?>" <?=$holiday['country_code']===$key?'selected':''?>><?=e($label)?></option><?php endforeach;?></select></label><label>Date<input type="date" name="date" value="<?=e($holiday['date'])?>" required></label><button class="button" name="action" value="edit">Save</button><button class="button button-danger" name="action" value="delete" formnovalidate data-confirm="Delete this holiday?">Delete</button></form><?php endforeach;?><?php if(!$holidays):?><p class="muted">No holidays.</p><?php endif;?></section><script>document.querySelectorAll('[data-confirm]').forEach(function(button){button.addEventListener('click',function(event){if(!window.confirm(button.dataset.confirm))event.preventDefault();});});</script><?php page_end();
