<?php
require __DIR__ . '/app/bootstrap.php'; require __DIR__ . '/app/layout.php';
$admin = require_permission('manage_users'); $pdo=db(); $error=''; $preview=$_SESSION['csv_preview']??null;
$types=['users'=>'Users','departments'=>'Departments','holidays'=>'Holidays','tickets'=>'Tickets'];
$headers=['users'=>['full_name','username','email','role','department'],'departments'=>['name','code'],'holidays'=>['date','label','country_code'],'tickets'=>['ticket_number','issue_escalator','subject','category','subcategory','department','employee_name','description','priority','status']];
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$action=(string)($_POST['action']??'');$type=(string)($_POST['type']??'');
    if($action==='preview'&&isset($types[$type])&&isset($_FILES['csv'])&&($_FILES['csv']['error']??1)===UPLOAD_ERR_OK&&($_FILES['csv']['size']??0)<=5*1024*1024){$handle=fopen($_FILES['csv']['tmp_name'],'rb');$rows=[];$errors=[];$line=0;$head=fgetcsv($handle);$expected=$headers[$type];if(!$head||array_map('trim',$head)!==$expected)$errors[]='Header must be: '.implode(',', $expected);else while(($row=fgetcsv($handle))!==false&&count($rows)<1000){$line++;if(count($row)!==count($expected)){$errors[]='Row '.($line+1).': expected '.count($expected).' columns.';continue;}$data=array_combine($expected,$row);foreach($expected as $key) $data[$key]=trim((string)$data[$key]);$holidayDate=DateTimeImmutable::createFromFormat('!Y-m-d',$data['date']??'');$validHolidayDate=$holidayDate&&$holidayDate->format('Y-m-d')===($data['date']??'');if($type==='users'&&(!$data['full_name']||!preg_match('/^[a-z0-9._-]{3,80}$/',$data['username'])||!filter_var($data['email'],FILTER_VALIDATE_EMAIL)||!$data['role']))$errors[]='Row '.($line+1).': invalid user fields.';elseif($type==='departments'&&(!$data['name']||!$data['code']))$errors[]='Row '.($line+1).': name and code are required.';elseif($type==='holidays'&&(!$validHolidayDate||!$data['label']))$errors[]='Row '.($line+1).': invalid holiday date or label.';elseif($type==='tickets'&&(!$data['subject']||!$data['category']||!$data['department']||!$data['employee_name']||!$data['description']))$errors[]='Row '.($line+1).': required ticket fields missing.';else $rows[]=$data;}fclose($handle);$_SESSION['csv_preview']=['type'=>$type,'rows'=>$rows,'errors'=>$errors];$preview=$_SESSION['csv_preview'];}
    elseif($action==='import'&&is_array($preview)&&$preview['rows']){try{$pdo->beginTransaction();foreach($preview['rows'] as $row){if($preview['type']==='departments')$pdo->prepare('INSERT INTO departments(name,code) VALUES(?,?)')->execute([$row['name'],$row['code']]);elseif($preview['type']==='holidays')$pdo->prepare('INSERT INTO company_holidays(`date`,label,country_code,holiday_type) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE label=VALUES(label),holiday_type=VALUES(holiday_type)')->execute([$row['date'],$row['label'],$row['country_code']?:'COMPANY',$row['country_code']==='COMPANY'?'company':'public']);elseif($preview['type']==='users'){$role=$pdo->prepare('SELECT id FROM roles WHERE slug=?');$role->execute([$row['role']]);$roleId=(int)$role->fetchColumn();if(!$roleId)throw new RuntimeException('Unknown role: '.$row['role']);$dept=$pdo->prepare('SELECT id FROM departments WHERE code=?');$dept->execute([$row['department']]);$deptId=$dept->fetchColumn()?:null;$temporary=strtoupper(bin2hex(random_bytes(5)));$pdo->prepare('INSERT INTO users(role_id,department_id,username,full_name,email,password_hash,must_change_password) VALUES(?,?,?,?,?,?,1)')->execute([$roleId,$deptId,$row['username'],$row['full_name'],$row['email'],password_hash($temporary,PASSWORD_DEFAULT)]); } }$pdo->commit();audit_admin_action((int)$admin['id'],'csv_imported',$preview['type'],null,['rows'=>count($preview['rows'])]);unset($_SESSION['csv_preview']);$preview=null;}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();$error='Import failed. Check duplicates and referenced roles/departments.';}}
}
page_start('CSV import',$admin); ?><div class="page-head"><div><p class="eyebrow">Super Admin</p><h1>CSV import</h1><p class="page-subtitle">Upload a CSV, review validation results, then explicitly confirm the import.</p></div></div><?php if($error):?><p class="auth-error"><?=e($error)?></p><?php endif;?><section><form method="post" enctype="multipart/form-data" class="compact-form"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="preview"><label>Import type<select name="type"><?php foreach($types as $key=>$label):?><option value="<?=$key?>"><?=e($label)?></option><?php endforeach;?></select></label><label>CSV file<input type="file" name="csv" accept=".csv,text/csv" required></label><button class="button">Validate CSV</button></form><p class="muted">Maximum 1,000 rows and 5 MB per upload. Required headers are selected by import type.</p></section><?php if($preview):?><section><h2>Preview: <?=e($types[$preview['type']])?></h2><p><?=count($preview['rows'])?> valid rows, <?=count($preview['errors'])?> errors.</p><?php if($preview['errors']):?><ul><?php foreach($preview['errors'] as $item):?><li><?=e($item)?></li><?php endforeach;?></ul><?php endif;?><?php if($preview['rows']):?><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="import"><button class="button" data-confirm="Import these valid rows?">Import valid rows</button></form><?php endif;?></section><?php endif;?><?php page_end();
