<?php
$tickets = [
 ['Open','Roster coverage for weekend maintenance','Repairs and Maintenance (R&M)','Performance','Capacity','27 Jul 2026','27 Jul 2026','—','Michael Lamb','Daniel Santos'],
 ['In Progress','Request for work-from-home arrangement','Strata Customer Care','Personal Requests','Work-from-Home (WFH) Request','27 Jul 2026','28 Jul 2026','—','Justine Lee-Daly','Ally Ramos'],
 ['Pending','Daily attendance follow-up','Strata Admin Specialist','Attendance','Daily Attendance','27 Jul 2026','29 Jul 2026','—','Angela Culbi','Mark Villanueva'],
 ['Closed','Client escalation: technical access','Strata Compliance Specialist','Performance','Technical','27 Jul 2026','30 Jul 2026','30 Jul 2026','Abby Hoff','Nina Cruz'],
];
$pill = ['Open'=>'open','In Progress'=>'in-progress','Pending'=>'pending','Closed'=>'closed'];
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Dashboard preview</title><link rel="icon" href="assets/favicon.svg"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="assets/css/app.css"></head><body><header class="topbar"><div class="brand"><img src="assets/stratastaff-logo.png" alt="Strata Staff Global"><span class="brand-divider"></span><div class="client-mark">JAMESONS<span>CNG PARTNERSHIP</span></div></div><nav class="nav"><a class="active" href="#">Tickets</a><a href="#">My assignments</a></nav><div class="account">Dashboard layout preview</div></header><main class="page"><div class="page-head"><div><p class="eyebrow">CNG / Jamesons Ticketing System</p><h1>Issues register</h1><p class="page-subtitle">A compact shared view of account concerns and escalations.</p></div><a class="button" href="#">Create ticket</a></div><div class="table-wrap"><table class="ticket-table"><thead><tr><?php foreach(['Status','Subject','Department','Category','Subcategory','Date Created','Date Updated','Date Closed','Assignee','Employee'] as $heading):?><th><?=htmlspecialchars($heading)?></th><?php endforeach;?></tr></thead><tbody><?php foreach($tickets as $ticket):?><tr><td><span class="pill pill-<?=$pill[$ticket[0]]?>"><?=htmlspecialchars($ticket[0])?></span></td><?php foreach(array_slice($ticket,1) as $i=>$value):?><td class="<?=$i>=4?'muted':($i===0?'subject':'')?>"><?=htmlspecialchars($value)?></td><?php endforeach;?></tr><?php endforeach;?></tbody></table></div></main></body></html>
