<?php
require __DIR__ . '/app/bootstrap.php';
if (!app_is_setup()) redirect('setup.php');
if (current_user()) redirect('index.php');
$error = '';
$roles = db()->query("SELECT id, name FROM roles WHERE slug <> 'super-admin' ORDER BY name")->fetchAll();
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    verify_csrf(); $name=trim($_POST['full_name']??''); $email=strtolower(trim($_POST['email']??'')); $username=strtolower(trim($_POST['username']??'')); $password=$_POST['password']??''; $roleId=(int)($_POST['role_id']??0);
    $validRole=db()->prepare("SELECT 1 FROM roles WHERE id=? AND slug <> 'super-admin'"); $validRole->execute([$roleId]); $existing=db()->prepare('SELECT 1 FROM users WHERE username=? OR email=?'); $existing->execute([$username,$email]);
    if($name===''||!filter_var($email,FILTER_VALIDATE_EMAIL)||!str_ends_with($email,'@stratastaff.com')||!preg_match('/^[a-z0-9._-]{3,80}$/',$username)||strlen($password)<12||!$validRole->fetchColumn()||$existing->fetchColumn()){$error='Enter valid details, a unique account, a @stratastaff.com email, and a password of at least 12 characters.';}else{db()->prepare("INSERT INTO users(role_id,username,full_name,email,password_hash,must_change_password,is_active,approval_status) VALUES(?,?,?,?,?,0,0,'pending')")->execute([$roleId,$username,$name,$email,password_hash($password,PASSWORD_DEFAULT)]);redirect('register.php?submitted=1');}
}
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Request an account</title><link rel="stylesheet" href="assets/css/app.css"></head><body class="auth-page"><main class="auth-shell"><section class="auth-card"><p class="auth-eyebrow">ACCOUNT ACCESS</p><h1>Request an account</h1><?php if(isset($_GET['submitted'])):?><p class="action-notice" role="status">Thank you. Your registration is waiting for Super Admin approval. Please wait a few minutes, then try signing in. If it is still pending, contact the developer or Super Admin.</p><p><a href="login.php">Return to sign in</a></p><?php else:?><?php if($error):?><p class="auth-error" role="alert"><?=e($error)?></p><?php endif;?><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><label>Full name<input name="full_name" required autocomplete="name"></label><label>Company email<input name="email" type="email" pattern=".+@stratastaff\.com" required autocomplete="email"></label><label>Username<input name="username" pattern="[A-Za-z0-9._-]{3,80}" required autocomplete="username"></label><label>Password<input name="password" type="password" minlength="12" required autocomplete="new-password"></label><label>Requested role<select name="role_id" required><option value="">Select a role</option><?php foreach($roles as $role):?><option value="<?=$role['id']?>"><?=e($role['name'])?></option><?php endforeach;?></select></label><button class="button">Submit registration</button></form><p><a href="login.php">Return to sign in</a></p><?php endif;?></section></main></body></html>
