<?php
declare(strict_types=1);
require __DIR__ . '/app/bootstrap.php';
require __DIR__ . '/app/tickets.php';
require __DIR__ . '/app/layout.php';
$user = require_permission('view_all_tickets');
if (($user['role_slug'] ?? '') === 'cng-admin') { http_response_code(403); exit('You do not have permission to access this action.'); }
require_non_team_member($user);
$pdo = db(); $notice = ''; $error = '';
$statuses = ['annual' => 'Annual', 'sick' => 'Sick', 'emergency' => 'Emergency', 'half_day' => 'Half-day', 'birthday' => 'Birthday', 'bereavement' => 'Bereavement', 'paternity' => 'Paternity', 'maternity' => 'Maternity', 'undertime' => 'Undertime'];
$canLog = ($user['role_slug'] ?? '') === 'team-leader' || user_can('manage_roles');
$selectedDate = request_string($_GET, 'date') ?: date('Y-m-d');
$selectedDateValue = DateTimeImmutable::createFromFormat('!Y-m-d', $selectedDate);
if (!$selectedDateValue || $selectedDateValue->format('Y-m-d') !== $selectedDate) $selectedDate = date('Y-m-d');
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    verify_csrf();
    if (!$canLog) { http_response_code(403); exit('You do not have permission to manage attendance.'); }
    $action = request_string($_POST, 'action') ?: 'save'; $attendanceId = (int) request_string($_POST, 'attendance_id');
    $attendanceDate = request_string($_POST, 'attendance_date'); $departmentId = (int) request_string($_POST, 'department_id');
    $status = request_string($_POST, 'status') ?: 'annual'; $headcountValue = request_string($_POST, 'headcount');
    $headcount = $headcountValue === '' ? 0 : (int) $headcountValue; $notes = request_string($_POST, 'notes'); $staffIds = posted_ids('staff_ids');
    $dateValue = DateTimeImmutable::createFromFormat('!Y-m-d', $attendanceDate); $departmentCheck = $pdo->prepare('SELECT id FROM departments WHERE id = ?'); $departmentCheck->execute([$departmentId]);
    $staffCheck = $pdo->query('SELECT id FROM staff_directory WHERE is_active = 1'); $validStaffIds = array_map('intval', $staffCheck->fetchAll(PDO::FETCH_COLUMN));
    if (!in_array($action, ['save', 'update'], true) || !$dateValue || $dateValue->format('Y-m-d') !== $attendanceDate || !$departmentCheck->fetchColumn() || !isset($statuses[$status]) || ($headcountValue !== '' && !ctype_digit($headcountValue)) || $headcount < 0 || !valid_ids($staffIds, $validStaffIds)) {
        $error = 'Choose a valid date, department, status, headcount, and staff list.';
    } elseif ($action === 'update' && $attendanceId < 1) { $error = 'Choose an attendance record to edit.'; }
    else {
        $pdo->beginTransaction();
        try {
            if ($action === 'update') {
                $existing = $pdo->prepare('SELECT id FROM team_attendance WHERE id = ?'); $existing->execute([$attendanceId]);
                if (!$existing->fetchColumn()) throw new InvalidArgumentException('Attendance record not found.');
                $pdo->prepare('UPDATE team_attendance SET attendance_date=?,department_id=?,logged_by=?,status=?,headcount=?,notes=? WHERE id=?')->execute([$attendanceDate, $departmentId, $user['id'], $status, $headcount, $notes ?: null, $attendanceId]);
            } else {
                $stmt = $pdo->prepare('INSERT INTO team_attendance(attendance_date,department_id,logged_by,status,headcount,notes) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE id=LAST_INSERT_ID(id), logged_by=VALUES(logged_by), status=VALUES(status), headcount=VALUES(headcount), notes=VALUES(notes)');
                $stmt->execute([$attendanceDate, $departmentId, $user['id'], $status, $headcount, $notes ?: null]); $attendanceId = (int) $pdo->lastInsertId();
            }
            $pdo->prepare('DELETE FROM team_attendance_leave WHERE attendance_id = ?')->execute([$attendanceId]); $insertLeave = $pdo->prepare('INSERT INTO team_attendance_leave(attendance_id,staff_id) VALUES(?,?)');
            foreach ($staffIds as $staffId) $insertLeave->execute([$attendanceId, $staffId]); $pdo->commit();
            redirect('team-attendance.php?date=' . rawurlencode($attendanceDate) . '&notice=' . ($action === 'update' ? 'updated' : 'saved'));
        } catch (Throwable $exception) { if ($pdo->inTransaction()) $pdo->rollBack(); $error = $exception instanceof InvalidArgumentException ? $exception->getMessage() : 'Attendance could not be saved.'; }
    }
}
$notice = ['saved' => 'Attendance logged.', 'updated' => 'Attendance updated.'][request_string($_GET, 'notice')] ?? '';
$departments = $pdo->query('SELECT id,name FROM departments ORDER BY name')->fetchAll(); $staff = $pdo->query('SELECT id,full_name,team_label FROM staff_directory WHERE is_active=1 ORDER BY full_name')->fetchAll();
$editId = (int) request_string($_GET, 'edit'); $editing = null; $selectedLeaveStaffIds = [];
if ($editId > 0) { $editQuery = $pdo->prepare('SELECT * FROM team_attendance WHERE id = ?'); $editQuery->execute([$editId]); $editing = $editQuery->fetch() ?: null; if ($editing) { $selectedLeave = $pdo->prepare('SELECT staff_id FROM team_attendance_leave WHERE attendance_id = ?'); $selectedLeave->execute([$editId]); $selectedLeaveStaffIds = array_map('intval', $selectedLeave->fetchAll(PDO::FETCH_COLUMN)); } }
$formDate = $editing['attendance_date'] ?? $selectedDate; $formDepartmentId = (int) ($editing['department_id'] ?? ($departments[0]['id'] ?? 0)); $formStatus = $editing['status'] ?? 'annual'; $formHeadcount = (int) ($editing['headcount'] ?? 0); $formNotes = $editing['notes'] ?? ''; $formStatuses = $statuses;
if ($formStatus !== '' && !isset($formStatuses[$formStatus])) $formStatuses[$formStatus] = 'Legacy: ' . $formStatus;
$summaryStmt = $pdo->prepare('SELECT ta.*, d.name AS department, u.full_name AS logger, (SELECT COUNT(*) FROM team_attendance_leave tal WHERE tal.attendance_id = ta.id) AS leave_count FROM team_attendance ta JOIN departments d ON d.id = ta.department_id JOIN users u ON u.id = ta.logged_by WHERE ta.attendance_date = ? ORDER BY d.name'); $summaryStmt->execute([$selectedDate]); $dayRows = $summaryStmt->fetchAll();
$leaveByAttendance = [];
if ($dayRows) { $ids = array_map('intval', array_column($dayRows, 'id')); $placeholders = implode(',', array_fill(0, count($ids), '?')); $leaveQuery = $pdo->prepare('SELECT tal.attendance_id, sd.full_name FROM team_attendance_leave tal JOIN staff_directory sd ON sd.id = tal.staff_id WHERE tal.attendance_id IN (' . $placeholders . ') ORDER BY sd.full_name'); $leaveQuery->execute($ids); foreach ($leaveQuery->fetchAll() as $leaveRow) $leaveByAttendance[(int) $leaveRow['attendance_id']][] = $leaveRow['full_name']; }
$recent = $pdo->query('SELECT ta.*, d.name AS department, u.full_name AS logger, (SELECT COUNT(*) FROM team_attendance_leave tal WHERE tal.attendance_id = ta.id) AS leave_count FROM team_attendance ta JOIN departments d ON d.id = ta.department_id JOIN users u ON u.id = ta.logged_by ORDER BY ta.attendance_date DESC, d.name LIMIT 20')->fetchAll();
page_start('Team Attendance', $user);
?>
<div class="attendance-screen">
<?php if ($notice): ?><p class="action-notice" role="status"><?= e($notice) ?></p><?php endif; ?><?php if ($error): ?><p class="auth-error" role="alert"><?= e($error) ?></p><?php endif; ?>
<section class="attendance-summary-panel"><div class="attendance-metrics"><div><span>Departments logged</span><strong><?= count($dayRows) ?></strong></div><div><span>Present teams</span><strong><?= count(array_filter($dayRows, static fn(array $row): bool => $row['status'] === 'annual')) ?></strong></div><div><span>Total headcount</span><strong><?= array_sum(array_map(static fn(array $row): int => (int) $row['headcount'], $dayRows)) ?></strong></div></div><form method="get" class="attendance-date-filter" data-auto-date-submit><div class="calendar-form-field calendar-date-picker" data-date-picker><span class="calendar-field-label">Viewing date</span><input type="hidden" name="date" value="<?= e($selectedDate) ?>" data-date-input><button type="button" class="filter-picker-trigger" data-date-trigger aria-expanded="false"><span class="filter-picker-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><rect x="3.5" y="5" width="17" height="15.5" rx="2"/><path d="M8 3.5v3M16 3.5v3M3.5 9.5h17"/></svg></span><span class="filter-picker-copy"><strong data-date-label><?= e(date('M j, Y', strtotime($selectedDate))) ?></strong></span><svg class="filter-picker-chevron" viewBox="0 0 24 24" aria-hidden="true"><path d="m7 9 5 5 5-5"/></svg></button><div class="filter-picker-menu date-picker-menu" data-date-menu hidden></div></div></form></section>
<div class="attendance-layout"><?php if ($canLog): ?><section class="attendance-form-panel"><div class="section-head"><div><h2><?= $editing ? 'Edit attendance record' : 'Log department coverage' ?></h2><p class="muted">Add or update attendance for the selected date.</p></div></div><form method="post" class="attendance-form"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="<?= $editing ? 'update' : 'save' ?>"><input type="hidden" name="attendance_id" value="<?= (int) ($editing['id'] ?? 0) ?>"><div class="calendar-form-field calendar-date-picker" data-date-picker><span class="calendar-field-label">Date</span><input type="hidden" name="attendance_date" required value="<?= e($formDate) ?>" data-date-input><button type="button" class="filter-picker-trigger" data-date-trigger aria-expanded="false"><span class="filter-picker-icon" aria-hidden="true"><svg viewBox="0 0 24 24"><rect x="3.5" y="5" width="17" height="15.5" rx="2"/><path d="M8 3.5v3M16 3.5v3M3.5 9.5h17"/></svg></span><span class="filter-picker-copy"><strong data-date-label><?= e(date('M j, Y', strtotime($formDate))) ?></strong></span><svg class="filter-picker-chevron" viewBox="0 0 24 24" aria-hidden="true"><path d="m7 9 5 5 5-5"/></svg></button><div class="filter-picker-menu date-picker-menu" data-date-menu hidden></div></div><label>Department<select name="department_id" required data-ui-select><?php foreach ($departments as $department): ?><option value="<?= (int) $department['id'] ?>"<?= $formDepartmentId === (int) $department['id'] ? ' selected' : '' ?>><?= e($department['name']) ?></option><?php endforeach; ?></select></label><label>Status<select name="status" required data-ui-select><?php foreach ($formStatuses as $key => $label): ?><option value="<?= e($key) ?>"<?= $formStatus === $key ? ' selected' : '' ?>><?= e($label) ?></option><?php endforeach; ?></select></label><label>Headcount<input type="number" name="headcount" min="0" value="<?= $formHeadcount ?>"></label><label>Staff on leave<details class="staff-picker"><summary>Select staff<?= $selectedLeaveStaffIds ? ' (' . count($selectedLeaveStaffIds) . ' selected)' : '' ?></summary><div class="staff-picker-options"><?php foreach ($staff as $member): ?><label><input type="checkbox" name="staff_ids[]" value="<?= (int) $member['id'] ?>"<?= in_array((int) $member['id'], $selectedLeaveStaffIds, true) ? ' checked' : '' ?>> <span><?= e($member['full_name']) ?></span><small><?= e($member['team_label']) ?></small></label><?php endforeach; ?></div></details></label><label class="is-wide">Notes<textarea name="notes" rows="3" placeholder="Optional attendance or coverage notes"><?= e($formNotes) ?></textarea></label><div><button class="button"><?= $editing ? 'Update attendance' : 'Save attendance' ?></button><?php if ($editing): ?> <a class="button button-secondary" href="team-attendance.php?date=<?= e($selectedDate) ?>">Cancel</a><?php endif; ?></div></form></section><?php endif; ?>
<section class="attendance-table-panel"><div class="section-head"><div><h2><?= e(date('M j, Y', strtotime($selectedDate))) ?> attendance</h2><p class="muted">These records appear on Team Calendar for the same date.</p></div><span class="section-count"><?= count($dayRows) ?> records</span></div><div class="table-wrap"><table class="ticket-table compact-table"><thead><tr><th>Department</th><th>Status</th><th>Headcount</th><th>Staff on leave</th><th>Notes</th><th>Logged by</th><?php if ($canLog): ?><th>Action</th><?php endif; ?></tr></thead><tbody><?php foreach ($dayRows as $row): ?><tr><td><?= e($row['department']) ?></td><td><span class="pill pill-pending"><?= e($statuses[$row['status']] ?? $row['status']) ?></span></td><td><?= (int) $row['headcount'] ?></td><td><?= e(implode(', ', $leaveByAttendance[(int) $row['id']] ?? []) ?: 'None') ?></td><td><?= e($row['notes'] ?: '-') ?></td><td class="muted"><?= e($row['logger']) ?></td><?php if ($canLog): ?><td><a href="team-attendance.php?date=<?= e($selectedDate) ?>&edit=<?= (int) $row['id'] ?>">Edit</a></td><?php endif; ?></tr><?php endforeach; ?><?php if (!$dayRows): ?><tr><td colspan="<?= $canLog ? '7' : '6' ?>" class="empty-table-cell">No attendance logged for this date.</td></tr><?php endif; ?></tbody></table></div></section></div>
<section class="attendance-table-panel"><div class="section-head"><div><h2>Recent attendance logs</h2><p class="muted">Latest coverage records across departments.</p></div><span class="section-count"><?= count($recent) ?> records</span></div><div class="table-wrap"><table class="ticket-table compact-table"><thead><tr><th>Date</th><th>Department</th><th>Status</th><th>Headcount</th><th>Staff on leave</th><th>Logged by</th><?php if ($canLog): ?><th>Action</th><?php endif; ?></tr></thead><tbody><?php foreach ($recent as $row): ?><tr><td><a href="team-attendance.php?date=<?= e($row['attendance_date']) ?>"><?= e($row['attendance_date']) ?></a></td><td><?= e($row['department']) ?></td><td><?= e($statuses[$row['status']] ?? $row['status']) ?></td><td><?= (int) $row['headcount'] ?></td><td><?= (int) $row['leave_count'] ?></td><td class="muted"><?= e($row['logger']) ?></td><?php if ($canLog): ?><td><a href="team-attendance.php?date=<?= e($row['attendance_date']) ?>&edit=<?= (int) $row['id'] ?>">Edit</a></td><?php endif; ?></tr><?php endforeach; ?><?php if (!$recent): ?><tr><td colspan="<?= $canLog ? '7' : '6' ?>" class="empty-table-cell">No attendance logs yet.</td></tr><?php endif; ?></tbody></table></div></section>
</div><?php page_end();
