<?php
require __DIR__ . '/app/bootstrap.php'; require __DIR__ . '/app/tickets.php'; require __DIR__ . '/app/layout.php';
$user = require_permission('view_all_tickets'); $id = (int) ($_GET['id'] ?? 0);
$q = db()->prepare('SELECT t.*,d.name department,a.full_name assignee FROM tickets t JOIN departments d ON d.id=t.department_id LEFT JOIN users a ON a.id=t.assignee_id WHERE t.id=? AND t.deleted_at IS NULL'); $q->execute([$id]); $ticket = $q->fetch(); if (!$ticket) { http_response_code(404); exit('Ticket not found.'); }
if ($_SERVER['REQUEST_METHOD'] === 'POST') { verify_csrf(); if (isset($_POST['comment']) && user_can('comment_tickets')) { $body=trim($_POST['comment']); if ($body !== '') { db()->prepare('INSERT INTO ticket_comments(ticket_id,user_id,body) VALUES(?,?,?)')->execute([$id,$user['id'],$body]); activity($id,$user['id'],'commented'); } } elseif (user_can('edit_tickets')) { $new=$_POST['status'] ?? $ticket['status']; if (in_array($new,['open','in_progress','pending','closed'],true) && ($new !== 'closed' || user_can('close_tickets'))) { db()->prepare('UPDATE tickets SET status=?,closed_at=?,assignee_id=? WHERE id=?')->execute([$new,$new==='closed'?date('Y-m-d H:i:s'):null,$_POST['assignee_id']?:null,$id]); activity($id,$user['id'],'updated',['status'=>$new]); notify_management('Ticket updated: '.$ticket['ticket_number'],$ticket['subject'].' - '.$new); } } redirect('ticket.php?id='.$id); }
$users=active_users(); $comments=db()->prepare('SELECT c.*,u.full_name FROM ticket_comments c JOIN users u ON u.id=c.user_id WHERE c.ticket_id=? ORDER BY c.created_at'); $comments->execute([$id]); $events=db()->prepare('SELECT a.*,u.full_name FROM ticket_activity a LEFT JOIN users u ON u.id=a.actor_id WHERE a.ticket_id=? ORDER BY a.created_at DESC'); $events->execute([$id]); page_start($ticket['subject'],$user); ?>
<p class="eyebrow"><?=e($ticket['ticket_number'])?></p><h1><?=e($ticket['subject'])?></h1><p class="page-subtitle"><?=e($ticket['department'])?> &middot; <?=e($ticket['category'])?></p>
<div class="page-actions"><?php if(user_can('edit_tickets')): ?><a class="button" href="edit-ticket.php?id=<?=$id?>">Edit details</a><?php endif; ?><?php if(user_can('delete_tickets')): ?><form class="inline-form" method="post" action="delete-ticket.php" onsubmit="return confirm('Soft-delete this ticket?');"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><input type="hidden" name="id" value="<?=$id?>"><button class="button button-danger">Delete ticket</button></form><?php endif; ?></div>
<div class="ticket-detail"><section><h2>Description</h2><p><?=nl2br(e($ticket['description']))?></p><dl><dt>Escalator</dt><dd><?=e($ticket['issue_escalator'])?></dd><dt>Employee</dt><dd><?=e($ticket['employee_name'])?></dd></dl></section><?php if(user_can('edit_tickets')): ?><section><h2>Workflow</h2><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><label>Status<select name="status"><?php foreach(['open'=>'Open','in_progress'=>'In Progress','pending'=>'Pending','closed'=>'Closed'] as $k=>$v): ?><option value="<?=$k?>" <?=$ticket['status']===$k?'selected':''?>><?=$v?></option><?php endforeach; ?></select></label><label>Assignee<select name="assignee_id"><option value="">Unassigned</option><?php foreach($users as $u): ?><option value="<?=$u['id']?>" <?=$ticket['assignee_id']==$u['id']?'selected':''?>><?=e($u['full_name'])?></option><?php endforeach; ?></select></label><button class="button">Save changes</button></form></section><?php endif; ?></div>
<section><h2>Comments</h2><?php foreach($comments as $c): ?><p><strong><?=e($c['full_name'])?></strong> <span class="muted"><?=e($c['created_at'])?></span><br><?=nl2br(e($c['body']))?></p><?php endforeach; ?><?php if(user_can('comment_tickets')): ?><form method="post"><input type="hidden" name="csrf_token" value="<?=e(csrf_token())?>"><label>Add comment<textarea name="comment" required rows="3"></textarea></label><button class="button">Add comment</button></form><?php endif; ?></section>
<section><h2>Activity</h2><?php foreach($events as $event): ?><p class="muted"><?=e($event['created_at'])?> - <?=e($event['full_name']??'System')?> <?=e($event['action'])?></p><?php endforeach; ?></section><?php page_end();
